### ISSUE TITLE
2425-W-007 - Structured Data Score

### ISSUE THREAD

**Issue by saumier** [culturecreates/nebula#27]
Reference doc https://docs.google.com/document/d/1HMc505SzRPeOKxhUsVgpAQtGJcypaGCHJ4kvkTgbqmM/edit

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/nebula/issues/28
- [ ] https://github.com/culturecreates/nebula/issues/30
- [x] W-7 Single event score using dereferencing in Nebula
- [ ] W-7 Batch score events from a list (100 urls)
```

**Comment by saumier** [comment]
@fjjulien This WO is also finished. Let me know if you have any questions. I can make a demo when needed.

**Comment by saumier** [comment]
@tammy-culture I have closed this WO 007.

**Comment by saumier** [comment]
@tammy-culture This WO is complete. Please send final invoice if not already done. Thx.

**Comment by saumier** [comment]
@tammy-culture This WO is complete. Please send final invoice if not already done. Thx.

**Comment by tammy-culture** [comment]
@saumier Done
