### ISSUE TITLE
2425-W-005 OSAC Event Data ETL

### ISSUE THREAD

**Issue by saumier** [culturecreates/nebula#31]
WO reference https://docs.google.com/document/d/1krRWkKYVh8woshxsS66bk5tFSyNsetIygu91PCVXtGA/edit#heading=h.phzh70cof3ne

```[tasklist]
### Tasks
- [ ] https://github.com/culturecreates/artsdata-planet-osac/issues/4
- [ ] https://github.com/culturecreates/artsdata-planet-osac/issues/1
- [ ] https://github.com/culturecreates/artsdata-planet-osac/issues/3
- [ ] 2425-W-005 Final Report
```
